linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  goimports:
    local-prefixes: lyrics-overlay
  errcheck:
    check-blank: true
    # Allow ignoring errors for common patterns
    check-type-assertions: false

issues:
  exclude-rules:
    # Exclude main.go to avoid Windows-specific imports
    - path: ^main\.go$
      linters:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - gofmt
        - goimports
        - misspell
    - path: _test\.go
      linters:
        - errcheck
        - unused
    # Exclude common false positives
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv).* is not checked"
      linters:
        - errcheck
    # Exclude non-critical config persistence in cleanup/toggle paths
    - text: "Error return value of `s\\.config\\.(UpdateOverlay|UpdateAuth|Save)` is not checked"
      linters:
        - errcheck
    - text: "Error return value of `s\\.server\\.Shutdown` is not checked"
      linters:
        - errcheck
    - text: "unused"
      linters:
        - unused
  # Increase max issues per linter to avoid failing on minor issues
  max-issues-per-linter: 50
  max-same-issues: 50

